'use server';

import { supabaseAdmin } from '@/lib/supabase-server';
import { revalidatePath } from 'next/cache';
import { requireAuth } from '@/lib/auth-guard';

// ─────────────────────────────────────────────────────────────────────────────
// FIX MED-01: All mutating actions now call requireAuth() to verify the caller
//             is authenticated with an appropriate role before executing.
//
// FIX MED-02: saveSettings now validates keys against an explicit allowlist to
//             prevent mass-assignment attacks on unexpected columns.
//
// FIX LOW-01: Raw internal error messages are no longer forwarded to clients.
// ─────────────────────────────────────────────────────────────────────────────

/** Explicit allowlist of keys that can be set via the settings page. */
const ALLOWED_SETTINGS_KEYS = [
  'station_name',
  'station_location',
  'currency',
  'timezone',
  'require_shift_for_session',
  'allow_debt_sessions',
  'max_debt_limit',
  'sms_notifications_enabled',
  'receipt_footer_text',
  'logo_url',
] as const;

type AllowedSettingKey = (typeof ALLOWED_SETTINGS_KEYS)[number];

export async function saveSettings(settings: Record<string, unknown>) {
  try {
    // MED-01: Require manager or super_admin role
    await requireAuth(['super_admin', 'manager']);

    // MED-02: Strip any keys not in the allowlist before writing to DB
    const sanitized: Partial<Record<AllowedSettingKey, unknown>> = {};
    for (const key of ALLOWED_SETTINGS_KEYS) {
      if (Object.prototype.hasOwnProperty.call(settings, key)) {
        sanitized[key] = settings[key];
      }
    }

    if (Object.keys(sanitized).length === 0) {
      return { success: false, error: 'No valid setting keys were provided.' };
    }

    // Get the single settings row id
    const { data: existing } = await supabaseAdmin
      .from('settings')
      .select('id')
      .limit(1)
      .single();

    if (!existing) {
      return { success: false, error: 'No settings row found. Run the SQL migration.' };
    }

    const { error } = await supabaseAdmin
      .from('settings')
      .update({ ...sanitized, updated_at: new Date().toISOString() })
      .eq('id', existing.id);

    if (error) {
      console.error('[SETTINGS] DB error:', error);
      return { success: false, error: 'Failed to save settings. Please try again.' };
    }

    revalidatePath('/settings');
    return { success: true };
  } catch (e: any) {
    console.error('[SETTINGS] Error:', e);
    // Return the auth error message (it's safe — generated by our own guard)
    if (e.message?.startsWith('Unauthenticated') || e.message?.startsWith('Forbidden')) {
      return { success: false, error: e.message };
    }
    return { success: false, error: 'An unexpected error occurred.' };
  }
}

export async function updatePricingRate(payload: {
  unit_type: 'kwh' | 'minutes' | 'hours';
  unit_quantity: number;
  rate: number;
}) {
  try {
    // MED-01: Only managers and super_admins can change pricing
    await requireAuth(['super_admin', 'manager']);

    // Basic numeric validation
    if (payload.rate <= 0 || payload.unit_quantity <= 0) {
      return { success: false, error: 'Rate and unit quantity must be positive numbers.' };
    }

    const { error: insertError } = await supabaseAdmin
      .from('pricing')
      .insert({
        unit_type: payload.unit_type,
        unit_quantity: payload.unit_quantity,
        rate: payload.rate,
        description: `GHS ${payload.rate} per ${payload.unit_quantity} ${payload.unit_type}`,
        is_active: true,
      })
      .select()
      .single();

    if (insertError) {
      console.error('[PRICING] Insert error:', insertError);
      return { success: false, error: 'Failed to update pricing. Please try again.' };
    }

    revalidatePath('/settings');
    return { success: true };
  } catch (e: any) {
    console.error('[PRICING] Error:', e);
    if (e.message?.startsWith('Unauthenticated') || e.message?.startsWith('Forbidden')) {
      return { success: false, error: e.message };
    }
    return { success: false, error: 'An unexpected error occurred.' };
  }
}

export async function togglePricingRate(id: string, active: boolean) {
  try {
    // MED-01: Only managers and super_admins can toggle pricing
    await requireAuth(['super_admin', 'manager']);

    const { error } = await supabaseAdmin
      .from('pricing')
      .update({ is_active: active })
      .eq('id', id);

    if (error) {
      console.error('[PRICING_TOGGLE] DB error:', error);
      return { success: false, error: 'Failed to update pricing status. Please try again.' };
    }

    revalidatePath('/settings');
    return { success: true };
  } catch (e: any) {
    console.error('[PRICING_TOGGLE] Error:', e);
    if (e.message?.startsWith('Unauthenticated') || e.message?.startsWith('Forbidden')) {
      return { success: false, error: e.message };
    }
    return { success: false, error: 'An unexpected error occurred.' };
  }
}
